name: Example

on: [push, pull_request]

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --all-extras --dev

      - name: Run ruff check
        run:
          uv run ruff check

  ruff-format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --all-extras --dev

      - name: Run ruff format check
        run:
          uv run ruff format --check

  mypy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: |
          uv sync --all-extras --dev

      - name: Run mypy check
        run:
          uv run mypy .
